# Generated by Django 5.2.8 on 2025-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_quiz_description_quiz_duration_minutes_quiz_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='0 أو فارغ تعني عدد محاولات غير محدود', null=True),
        ),
    ]
