# Generated by Django 5.2.8 on 2025-12-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_homework_end_time_homework_start_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('single', 'Single choice'), ('multi', 'Multiple choice'), ('text', 'Text answer')], default='single', max_length=10),
        ),
    ]
